name: Google Maps
version: 1.02
description: Easily integrate google maps into your website
url: https://github.com/krve/statamic-google-maps
developer: Kristoffer Vestergaard
developer_url: https://krve.io
